from django.db import models

# Create your models here.
class FuneralPolicy(models.Model):

    gender_choices = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]

    policy_search = models.IntegerField()
    ID_search = models.IntegerField(unique=True)
    time_stamp = models.DateField()
    report_period_start = models.DateTimeField()
    report_period_end = models.DateTimeField()
    administrator = models.CharField(max_length=100)  
    insurer_name = models.CharField(max_length=200)
    client_identifier = models.IntegerField()
    division_identifier = models.IntegerField()
    sub_scheme_name = models.CharField(max_length=200)
    policy_number = models.CharField(max_length=200)
    product_name = models.CharField(max_length=200)
    product_option = models.IntegerField()
    policy_commencement_date = models.DateField()
    policy_expiry_date = models.DateField()
    term_of_policy = models.IntegerField()
    policy_status = models.CharField(max_length=200)
    policy_status_date = models.DateField()
    new_policy_indicator = models.IntegerField()
    sales_channel = models.CharField(max_length=200)
    cancelled_by = models.IntegerField()
    death_indicator = models.CharField(max_length=200)
    premium_frequency = models.IntegerField()
    premium_type = models.CharField(max_length=200)
    death_original_sum_insured = models.FloatField()
    death_cover = models.CharField(max_length=200)
    death_current_sum_insured = models.FloatField()
    reinsurer_name = models.CharField(max_length=200)
    death_current_ri_sum_insured = models.FloatField()
    death_ri_premium = models.FloatField()
    death_ri_percent = models.FloatField()
    total_premium_collected = models.IntegerField()
    total_premium_payable = models.FloatField()
    total_premium_subsidy = models.FloatField()
    total_reinsurance_premium = models.FloatField()
    total_reinsurance_premium_payable = models.FloatField()
    total_financial_reinsurance_cashflows = models.FloatField()
    total_financial_reinsurance_payable = models.FloatField()
    commission_frequency = models.IntegerField()
    commission = models.FloatField()
    binder_fees = models.FloatField()
    outsourcing_fees = models.FloatField()
    marketing_fees = models.FloatField()
    management_fees = models.FloatField()
    claims_handling_fees = models.FloatField()
    total_gross_claim_amount = models.FloatField()
    gross_claim_paid = models.FloatField()
    reinsurance_recoveries = models.IntegerField()
    principal_surname = models.CharField(max_length=200)
    principal_firstname = models.CharField(max_length=200)
    principal_initials = models.CharField(max_length=200)
    principal_id = models.BigIntegerField(unique=True)
    principal_gender = models.CharField(max_length=200, choices=gender_choices)
    principal_date_of_birth = models.DateField()
    principal_physical_address = models.CharField(max_length=255)
    principal_postal_code = models.IntegerField()
    principal_email = models.EmailField()
    income_group = models.IntegerField()
    spouse_indicator = models.CharField(max_length=200)
    number_adult_dependants = models.IntegerField()
    number_child_dependants = models.IntegerField()
    number_extended_family = models.IntegerField()
    spouse_surname = models.CharField(max_length=200)
    spouse_firstname = models.CharField(max_length=200)
    spouse_initials = models.CharField(max_length=200)
    spouse_id = models.IntegerField(unique=True)

    spouse_gender = models.CharField(max_length=10, choices=gender_choices)

    spouse_date_of_birth = models.DateField()
    spouse_cover_amount = models.FloatField()
    spouse_cover_commencement_date = models.DateField()

    dependent_1_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_1_date_of_birth = models.DateField()
    dependent_1_type = models.CharField(max_length=200)
    dependent_1_cover_amount = models.IntegerField()
    dependent_1_cover_commencement_date = models.DateTimeField()

    dependent_2_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_2_date_of_birth = models.DateField()
    dependent_2_type = models.CharField(max_length=200)
    dependent_2_cover_amount = models.IntegerField()
    dependent_2_cover_commencement_date = models.DateTimeField()

    dependent_3_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_3_date_of_birth = models.DateField()
    dependent_3_type = models.CharField(max_length=200)
    dependent_3_cover_amount = models.IntegerField()
    dependent_3_cover_commencement_date = models.DateTimeField()

    dependent_4_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_4_date_of_birth = models.DateField()
    dependent_4_type = models.CharField(max_length=200)
    dependent_4_cover_amount = models.IntegerField()
    dependent_4_cover_commencement_date = models.DateTimeField()

    dependent_5_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_5_date_of_birth = models.DateField()
    dependent_5_type = models.CharField(max_length=200)
    dependent_5_cover_amount = models.IntegerField()
    dependent_5_cover_commencement_date = models.DateTimeField()

    dependent_6_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_6_date_of_birth = models.DateField()
    dependent_6_type = models.CharField(max_length=200)
    dependent_6_cover_amount = models.IntegerField()
    dependent_6_cover_commencement_date = models.DateTimeField()

    dependent_7_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_7_date_of_birth = models.DateField()
    dependent_7_type = models.CharField(max_length=200)
    dependent_7_cover_amount = models.IntegerField()
    dependent_7_cover_commencement_date = models.DateTimeField()

    dependent_8_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_8_date_of_birth = models.DateField()
    dependent_8_type = models.CharField(max_length=200)
    dependent_8_cover_amount = models.IntegerField()
    dependent_8_cover_commencement_date = models.DateTimeField()

    dependent_9_gender = models.CharField(max_length=10, choices=gender_choices)
    dependent_9_date_of_birth = models.DateField()
    dependent_9_type = models.CharField(max_length=200)
    dependent_9_cover_amount = models.IntegerField()
    dependent_9_cover_commencement_date = models.DateTimeField()

    dpip = models.CharField(max_length=200)
    reference_number = models.IntegerField(unique=True)
    policy_start_date = models.DateField()

    def __str__(self):
        return f"{self.policy_number} - {self.insurer_name} - {self.policy_start_date}"

class IndluLoanData(models.Model):

    gender_choices = [
        ('Male', 'male'),
        ('Female', 'female')
    ]

    report_data = models.DateField()
    client_ref = models.BigIntegerField()
    loan_ref_Id = models.IntegerField()
    status = models.CharField(max_length=250)
    close_date = models.DateField()
    NT = models.CharField(max_length=250)
    payment_method = models.CharField(max_length=250)
    merchant = models.CharField(max_length=250)
    province = models.CharField(max_length=250)
    disbursment_date = models.DateField()
    disbursement_month = models.IntegerField()
    application_score = models.IntegerField()
    risk_band = models.IntegerField()
    debt_book = models.CharField(max_length=250)
    agency = models.CharField(max_length=250)
    special_circumstance = models.CharField(max_length=250, null=True, blank=True)
    sector = models.CharField(max_length=250)
    job_description = models.CharField(max_length=250)
    last_payment_date = models.DateField()
    last_payment_month = models.IntegerField()
    gender = models.CharField(max_length=250, choices = gender_choices)
    employer = models.CharField(max_length=250)
    loan_amount = models.FloatField()
    int_rate = models.FloatField()
    loan_term = models.IntegerField()
    remaining_term = models.IntegerField()
    CD_move = models.IntegerField()
    CD_current_month = models.IntegerField(null=True, blank=True)
    CD_Oct_2023 = models.IntegerField(null=True, blank=True)
    CD_Sep_2023 = models.IntegerField(null=True, blank=True)
    CD_Aug_2023 = models.IntegerField(null=True, blank=True)
    CD_Jul_2023 = models.IntegerField(null=True, blank=True)
    CD_Jun_2023 = models.IntegerField(null=True, blank=True)
    CD_May_2023 = models.IntegerField(null=True, blank=True)
    CD_Apr_2023 = models.IntegerField(null=True, blank=True)
    CD_Mar_2023 = models.IntegerField(null=True, blank=True)
    CD_Feb_2023 = models.IntegerField(null=True, blank=True)
    CD_Jan_2023 = models.IntegerField(null=True, blank=True)
    CD_Dec_2023 = models.IntegerField(null=True, blank=True)
    CD_Nov_2023 = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.client_ref} - {self.loan_ref_Id} - {self.status}"

class SmartAdvanceCredit(models.Model):

    gender_choices = [
        ('Male', 'male'),
        ('female', 'Female')
    ]

    refId = models.IntegerField(unique=True)
    batch_number = models.IntegerField()
    create_date = models.DateField()
    transmission_date = models.DateField()
    file_name = models.CharField(max_length=250)
    loan_ref = models.IntegerField()
    policy_status = models.IntegerField()
    policy_commencement_date = models.DateTimeField()
    policy_expiry_date = models.DateField()
    term_of_policy = models.IntegerField()
    policy_status_date = models.DateTimeField()
    new_policy_indicator = models.CharField(max_length=250)
    sales_channel = models.CharField(max_length=250)
    death_premium = models.FloatField()
    ptd_premium = models.IntegerField()
    retrenchment_premium = models.IntegerField()
    death_original_sum_assured = models.FloatField()
    death_current_sum_assured = models.FloatField()
    PTD_current_sum_assured = models.FloatField()
    retrenchment_current_sum_assured = models.FloatField()
    total_policy_premium_collected = models.FloatField()
    total_policy_premium_payable = models.FloatField()
    original_loan_balance = models.FloatField()
    current_outstanding_balance = models.FloatField()
    installment_amount = models.FloatField()
    principal_surname = models.CharField(max_length=250)
    principal_first_name = models.CharField(max_length=250)
    principal_initials = models.CharField(max_length=50)
    principal_ID = models.BigIntegerField(unique=True)
    principal_gender = models.CharField(max_length=250, choices=gender_choices)
    principal_date_of_birth = models.DateField()
    principal_member_physical_address = models.CharField(max_length=250)
    principal_member_email_address = models.EmailField()
    principal_telephone_number = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=250)
    PTD_original_sum_assured = models.IntegerField()
    retrenchment_original_sum_assured = models.IntegerField()
    income_group = models.CharField(max_length=250)
    admin_binder_fees = models.IntegerField()
    commission = models.IntegerField()
    old_provider = models.CharField(max_length=250, null=True, blank=True)