# Generated by Django 5.0.1 on 2024-01-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralpolicies',
            name='principal_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200),
        ),
    ]
