# Generated by Django 5.0.1 on 2024-01-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0006_indluloandata_account_balance_active_charge_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralpolicy',
            name='ID_search',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='administrator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='binder_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='cancelled_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='claims_handling_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='client_identifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='commission_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_cover',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_current_ri_sum_insured',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_current_sum_insured',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_indicator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_original_sum_insured',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_ri_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_ri_premium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_1_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_1_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_1_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_1_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_2_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_2_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_2_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_2_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_3_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_3_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_3_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_3_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_4_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_4_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_4_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_4_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_4_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_5_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_5_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_5_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_5_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_5_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_6_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_6_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_6_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_6_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_6_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_7_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_7_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_7_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_7_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_7_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_8_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_8_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_8_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_8_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_8_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_9_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_9_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_9_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_9_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_9_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='division_identifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dpip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='gross_claim_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='income_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='insurer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='management_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='marketing_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='new_policy_indicator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='number_adult_dependants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='number_child_dependants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='number_extended_family',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='outsourcing_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_search',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='premium_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='premium_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_initials',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_physical_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='product_option',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='reference_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='reinsurance_recoveries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='reinsurer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='report_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='report_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='sales_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_cover_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_cover_commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_indicator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_initials',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='sub_scheme_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='term_of_policy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='time_stamp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_financial_reinsurance_cashflows',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_financial_reinsurance_payable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_gross_claim_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_premium_collected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_premium_payable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_premium_subsidy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_reinsurance_premium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_reinsurance_premium_payable',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
