# Generated by Django 5.0.1 on 2024-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0009_remove_funeralpolicy_dependent_1_cover_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_1_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_1_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_1_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_1_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_1_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_2_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_2_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_2_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_2_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_2_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_3_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_3_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_3_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_3_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_3_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_4_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_4_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_4_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_4_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_4_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_5_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_5_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_5_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_5_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_5_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_6_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_6_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_6_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_6_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_6_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_7_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_7_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_7_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_7_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_7_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_8_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_8_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_8_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_8_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_8_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_9_cover_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_9_cover_commencement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_9_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_9_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='funeralpolicy',
            name='dependent_9_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
