# Generated by Django 5.0.1 on 2024-01-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0010_funeralpolicy_dependent_1_cover_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_search',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
