# Generated by Django 5.0.1 on 2024-01-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0012_alter_funeralpolicy_id_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indluloandata',
            name='close_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indluloandata',
            name='disbursment_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indluloandata',
            name='last_payment_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indluloandata',
            name='report_data',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
