# Generated by Django 5.0.1 on 2024-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0013_alter_indluloandata_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_1_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_1_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_2_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_2_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_3_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_3_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_4_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_4_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_5_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_5_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_6_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_6_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_7_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_7_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_8_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_8_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_9_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='dependent_9_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_expiry_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_start_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='policy_status_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='principal_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='report_period_end',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='report_period_start',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_cover_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='time_stamp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='create_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='policy_commencement_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='policy_expiry_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='policy_status_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='principal_date_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='transmission_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
