# Generated by Django 5.0.1 on 2024-01-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0014_alter_funeralpolicy_dependent_1_cover_commencement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralpolicy',
            name='binder_fees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='claims_handling_fees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='commission',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_current_ri_sum_insured',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_current_sum_insured',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_original_sum_insured',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_ri_percent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='death_ri_premium',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='gross_claim_paid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='management_fees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='marketing_fees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='outsourcing_fees',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='spouse_cover_amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_financial_reinsurance_cashflows',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_financial_reinsurance_payable',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_gross_claim_amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_premium_payable',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_premium_subsidy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_reinsurance_premium',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='funeralpolicy',
            name='total_reinsurance_premium_payable',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indluloandata',
            name='int_rate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='indluloandata',
            name='loan_amount',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='PTD_current_sum_assured',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='current_outstanding_balance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='death_current_sum_assured',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='death_original_sum_assured',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='death_premium',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='installment_amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='original_loan_balance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='retrenchment_current_sum_assured',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='total_policy_premium_collected',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='total_policy_premium_payable',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
