# Generated by Django 5.0.1 on 2024-01-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0016_alter_indluloandata_cd_move_alter_indluloandata_nt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indluloandata',
            old_name='disbursement_month',
            new_name='disbursment_month',
        ),
    ]
