# Generated by Django 5.0.1 on 2024-01-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0017_rename_disbursement_month_indluloandata_disbursment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='principal_ID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
