# Generated by Django 5.0.1 on 2024-01-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0018_alter_smartadvancecredit_principal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartadvancecredit',
            name='refId',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
